# 9. Cancellation

- 코틀린 코루틴에서 굉장히 중요한 기능 중 하나는 취소(cancellation) 이다.  
  취소는 매우 중요하기에 중단 함수를 사용하는 몇몇 클래스와 라이브러리는 취소를 반드시 지원한다.  
  코루틴을 어떻게 취소할 수 있는지 살펴보자.

---

## 기본적인 취소

- `Job` 인터페이스는 취소하게 하는 `cancel()` 메소드를 가지며, 이 메소드를 호출하면 아래와 같은 효과가 일어난다.
  - 호출한 코루틴은 첫 번째 중단점(아래 코드에서는 `delay()`)에서 `Job` 을 끝낸다.
  - `Job` 이 자식을 가진다면 자식들 또한 취소한다. 하지만 부모는 영향을 받지 않는다.
  - `Job` 이 취소되면 취소된 `Job` 은 새로운 코루틴의 부모로 사용될 수 없다.
  - 취소된 `Job` 은 `CANCELLING` 상태가 되었다가 `CANCELLED` 상태로 바뀐다.

```kt
suspend fun main(): Unit = coroutineScope {
	val job = launch {
		repeat(1_000) { i ->
			delay(200)
			println("Printing $i")
		}
	}

	delay(1100)
	job.cancel()
	job.join()
	println("Cancelled successfully")
}

// Printing 0
// Printing 1
// Printing 2
// Printing 3
// Printing 4
// Cancelled successfully
```

- `cancel()` 함수에 각기 다른 예외를 인자로 넣는 방법을 활용하면 취소의 원인을 명확하게 알 수 있다.  
  코루틴을 취소하기 위해 사용되는 예외는 반드시 `CancellationException` 이어야 하기 때문에  
  인자로 사용되는 예외는 반드시 이 타입의 서브타입이어야 한다.
- `cancel()` 이 호출된 뒤, 다음 작업을 진행하기 전 취소 과정이 완료되는 것을 기다리기 위해 `join()` 을 사용하는 것이 일반적이다.  
  `join()` 을 호출하지 않으면 race condition이 발생할 수 있다.  
  아래 코드는 `join()` 호출이 없기에 `"Cancelled successfully"` 뒤에 `"Printing 4"` 가 출력된다.

```kt
suspend fun main(): Unit = coroutineScope {
	val job = launch {
		repeat(1_000) { i ->
			delay(100)
			Thread.sleep(100) // 오래 걸리는 연산이라 가정
			println("Printing $i")
		}
	}

	delay(1000)
	job.cancel()
	println("Cancelled successfully")
}

// Printing 0
// Printing 1
// Printing 2
// Cancelled successfully
// Printing 3
// Printing 4
```

- `job.join()` 을 추가하면 코루틴이 취소를 마칠 때까지 기다리므로 race condition이 발생하지 않는다.

```kt
suspend fun main(): Unit = coroutineScope {
	val job = launch {
		repeat(1_000) { i ->
			delay(100)
			Thread.sleep(100) // 오래 걸리는 연산이라 가정
			println("Printing $i")
		}
	}

	delay(1000)
	job.cancel()
	job.join()
	println("Cancelled successfully")
}

// Printing 0
// Printing 1
// Printing 2
// Printing 3
// Printing 4
// Cancelled successfully
```

- `kotlinx.coroutines` 라이브러리는 이 둘을 함께 호출할 수 있는 간단한 방법으로 `cancelAndJoin()` 이라는 편리한 확장 함수를 제공한다.

```kt
suspend fun main(): Unit = coroutineScope {
	val job = launch {
		repeat(1_000) { i ->
			delay(200)
			println("Printing $i")
		}
	}

	delay(1100)
	job.cancelAndJoin()
	println("Cancelled successfully")
}

// Printing 0
// Printing 1
// Printing 2
// Printing 3
// Printing 4
// Cancelled successfully
```

---

## 취소는 어떻게 동작하는가?

- `Job` 이 취소되면 `CANCELLING` 상태로 바뀐다. 그리고 상태가 바뀐 첫 번째 중단점에서 `CancellationException` 을 던진다.  
  예외는 try-catch 문으로 잡을 수도 있지만, 다시 던지는 것이 좋다.

```kt
suspend fun main(): Unit = coroutineScope {
	val job = Job()
	launch(job) {
		try {
			repeat(1_000) { i ->
				delay(200)
				println("Printing $i")
			}
		} catch(e: CancellationException) {
			println(e)
			throw e
		}
	}

	delay(1100)
	job.cancelAndJoin()
	println("Cancelled successfully")
	delay(1000)
}

// Printing 0
// Printing 1
// Printing 2
// Printing 3
// JobCancellationException...
// Cancelled successfully
```

- 여기서 취소된 코루틴이 단지 멈추는 것이 아니라, 내부적으로 예외를 사용해 취소되었다는 것을 명심해야 한다.  
  따라서 `finally` block 안에서 모든 것을 처리할 수 있다.

```kt
suspend fun main(): Unit = coroutineScope {
	val job = Job()
	launch(job) {
		try {
			delay(Random.nextLong(2000))
			println("Done")
		} finally {
			print("Will always be printed")
		}
	}
	delay(1000)
	job.cancelAndJoin()
}

// Will always be printed
// (또는)
// Done
// Will always be printed
```

---

## 취소 중 코루틴을 한 번 더 호출하기

- 코루틴이 실제로 종료되기 전에 `CancellationException`을 catch하고 좀 더 많은 연산을 수행할 수 있으므로,  
  후처리 과정에 제한이 있을지 궁금할 것이다. 코루틴은 모든 자원을 정리할 필요가 있는 한 계속해서 실행될 수 있다.  
  하지만 정리 과정 중에는 중단을 허용하지 않는다. `Job` 이 이미 `CANCELLING` 상태가 되었기 때문에,  
  다시 중단되거나 다른 코루틴을 시작하는 것은 불가능하다. 다른 코루틴을 시작하려 하면 그냥 무시해 버린다.  
  중단하려 하면 `CancellationException` 을 던진다.

```kt
suspend fun main(): Unit = coroutineScope {
	val job = Job()
	launch(job) {
		try {
			delay(2000)
			println("Job is done")
		} finally {
			println("Finally")
			launch { // 무시된다
				println("Will not be printed")
			}
			delay(1000) // 여기서 예외가 발생한다.
			println("Will not be printed")
		}
	}
	delay(1000)
	job.cancelAndJoin()
	println("Cancel done")
}

// (1초 후)
// Finally
// Cancel done
```

- 데이터베이스의 변경 사항을 rollback 하는 것처럼 코루틴이 이미 취소되었을 때 중단 함수를 반드시 호출해야 하는 경우가  
  있을 수도 있다. 이런 경우, 함수 call을 `withContext(NonCancellable)` 로 wrapping하는 방식이 많이 사용된다.  
  `withContext()` 가 어떻게 작동하는지는 이후 살펴보겠지만, 중요한 점은 코드 블록의 context를 바꾼다는 것이다.  
  `withContext()` 내부에서는 취소될 수 없는 `Job` 인 `NonCancellable` 객체를 사용한다.  
  따라서 블록 내에서 `Job` 은 `ACTIVE` 상태를 유지하며, 중단 함수를 원하는 만큼 호출할 수 있다.

```kt
suspend fun main(): Unit = coroutineScope {
	val job = Job()
	launch(job) {
		try {
			delay(200)
			println("Coroutine finished")
		} finally {
			println("Finally")
			withContext(NonCancellable) {
				delay(1000L)
				println("Cleanup done")
			}
		}
	}
	delay(100)
	job.cancelAndJoin()
	println("Done")
}

// Finally
// Cleanup done
// Done
```

---

## `invokeOnCompletion()`

- 자원을 해제하는 데 자주 사용되는 또다른 방법은 `Job`의 `invokeOnCompletion` 메소드를 호출하는 것이다.  
  이 메소드는 `Job` 이 `COMPLETED` 나 `CANCELLED` 와 같은 최종 상태에 도달했을 때 호출될 handler를 지정하는 역할을 한다.

```kt
suspend fun main(): Unit = coroutineScope {
	val job = launch { delay(1000) }
	job.invokeOnCompletion { exception: Throwable? ->
		println("Finished")
	}
	delay(400)
	job.cancelAndJoin()
}

// Finished
```

- 만약 `Job` 이 `invokeOnCompletion()` 이 호출되기 전 완료된다면, handler는 즉시 호출된다.  
  onCancelling과 invokeImmediately 파라미터를 사용하면 핸들러의 동작 방식을 변경할 수도 있다.
  - onCancelling: true면 `CANCELLED` 가 아닌 `CANCELLING` 상태에서 handler가 호출된다. 기본 값은 false이다.
  - invokeImmediately: 코루틴이 이미 원하는 상태일 때 handler가 지정되었다면, handler를 즉시 호출할지 여부를 결정한다. 기본 값은 true이다.

```kt
suspend fun main(): Unit = coroutineScope {
	val job = launch {
		delay(Random.nextLong(2400))
		println("Finished")
	}
	delay(800)
	job.invokeOnCompletion { exception: Throwable? ->
		println("Will always be printed")
		println("The exception was: $exception")
	}
	delay(800)
	job.cancelAndJoin()
}

// Will always be printed
// The exception was: kotlinx.coroutines.JobCancellationException
// (또는)
// Finished
// Will always be printed
// The exception was: null
```

- `invokeOnCompletion()` 은 취소하는 중에 동기적으로 호출되며, 실행될 스레드를 지정할 수 없다.

---

## 중단될 수 없는 것을 중단하기

- 취소는 중단점에서 일어나기 때문에, 중단점이 없으면 취소할 수 없다.  
  그렇다면 중단점이 없는 함수에서 취소를 어떻게 할 수 있을까?

```kt
suspend fun main(): Unit = coroutineScope {
	val job = Job()
	launch(job) {
		repeat(1_000) { i ->
			Thread.sleep(200) // file open 등의 복잡한 작업
			println("Printing $i")
		}
	}
	delay(1000)
	job.cancelAndJoin()
	println("Cancelled successfully")
	delay(1000)
}

// Printing 0
// Printing 1
// Printing 2
// ... (1000까지)
```

- 이런 상황에 대처하는 몇 가지 방법이 있다. 첫 번째는 `yield()` 를 주기적으로 호출하는 것이다.  
  `yield()` 는 코루틴을 중단하고, 즉시 재실행한다. 중단점이 생겼기 때문에 취소를 포함해 중단 중에 필요한 모든 작업을 할 수 있는 기회가 주어진다.

```kt
suspend fun main(): Unit = coroutineScope {
	val job = Job()
	launch(job) {
		repeat(1_000) { i ->
			Thread.sleep(200) // file open 등의 복잡한 작업
			yield()
			println("Printing $i")
		}
	}
	delay(1000)
	job.cancelAndJoin()
	println("Cancelled successfully")
	delay(1000)
}

// Printing 0
// Printing 1
// Printing 2
// Printing 3
// Printing 4
// Cancelled successfully
```

- 중단 가능하지 않으면서 CPU-intensive한 연산들이 중단 함수에 있다면, 각 연산들 사이에 `yield()` 를 사용하는 것이 좋다.

```kt
suspend fun cpuIntensiveOperations() = withContext(Dispatchers.Default) {
	cpuIntensiveOperation1()
	yield()
	cpuIntensiveOperation2()
	yield()
	cpuIntensiveOperation3()
}
```

- 또 다른 방법은 `Job` 의 상태를 추적하는 것이다. 코루틴 빌더 내의 this(리시버)는 빌더의 scope를 참조한다.  
  예를 들어 `CoroutineScope` 는 coroutineContext 프로퍼티를 사용해 참조할 수 있는 context를 가진다.

```kt
public val CoroutineScope.isActive: Boolean
	get() = coroutineScope[Job]?.isActive ?: true
```

- 위 isActive 프로퍼티를 사용해 `Job` 의 활성화 여부를 파악할 수 있고, active하지 않다면 연산을 중단할 수도 있다.

```kt
suspend fun main(): Unit = coroutineScope {
	val job = Job()
	launch(job) {
		do {
			Thread.sleep(200)
			println("Printing")
		} while (isActive)
	}
	delay(1100)
	job.cancelAndJoin()
	println("Cancelled successfully")
}

// Printing
// Printing
// Printing
// Printing
// Printing
// Printing
// Cancelled successfully
```

- 또 다른 방법으로 `Job` 이 `ACTIVE` 가 아니라면 `CancellationException` 을 던지는 `ensureActive()` 함수를 사용할 수 있다.

```kt
suspend fun main(): Unit = coroutineScope {
	val job = Job()
	launch(job) {
		repeat(1000) { num ->
			Thread.sleep(200)
			ensureActive()
			println("Printing $num")
		}
	}
	delay(1100)
	job.cancelAndJoin()
	println("Cancelled successfully")
}

// Printing 0
// Printing 1
// Printing 2
// Printing 3
// Printing 4
// Cancelled successfully
```

- 위 두 함수 모두 다른 코루틴이 실행할 수 있는 기회를 준다는 점에서 결과는 비슷하지만, 이 둘은 매우 다르다.  
  `ensureActive()` 는 `CoroutineScope` 또는 `CoroutineContext` 안에서 호출되어야 한다.  
  이 함수가 하는 일은 `Job` 이 `ACTIVE` 가 아니면 예외를 던지는 것이다.  
  일반적으로 `ensureActive()` 가 좀 더 가벼워 선호된다.  
  `yield()` 함수는 전형적인 최상위 중단 함수이다. Scope가 필요하지 않기에 일반적인 중단 함수에서도 사용될 수 있다.  
  단, 중단하고 재개하는 일을 하기에 thread pool을 가진 dispatcher를 사용하면 스레드가 바뀌는 문제가 발생할 수 있다.  
  `yield()` 는 CPU 사용량이 크거나, thread를 blocking하는 중단 함수에서 자주 사용된다.

---

## `suspendCancellableCoroutine()`

- 이 함수는 `suspendCoroutine()`과 비슷하지만, `Continuation` 객체를 몇 가지 메소드가 추가된  
  `CancellableContinuation<T>` 로 wrapping한다. 가장 중요한 메소드는 코루틴이 취소되었을 때의  
  행동을 정의하는 `invokeOnCancellation()` 메소드이다. 이 메소드는 라이브러리의 실행을 취소하거나, 자원을 해제할 때 주로 사용된다.

```kt
suspend fun someTask() = suspendCancellableCoroutine { cont ->
	cont.invokeOnCancellation {
		// 정리 작업 수행
	}
	// 나머지 구현 부분
}
```

- `CancellableContinuation<T>` 에서도 isActive, isCompleted, isCancelled 프로퍼티를 사용해  
  `Job` 의 상태를 확인할 수 있으며, `Continuation` 을 취소할 때 취소가 되는 원인을 추가적으로 제공할 수 있다.

---
