# 오류

- 다른 언어와 Go의 오류 처리 방식은 매우 다르다. 예외(exception)에 익숙한 사람들에게는 Go의 접근 방식이 매우 낯설 수 있다.  
  하지만 Go의 접근법에는 견고한 소프트웨어 엔지니어링 원칙이 있다. 이번에는 Go에서 오류를 처리하는 방식을 살펴보자.  
  또한 실행을 중지해야 하는 오류를 처리하기 위핸 Go 시스템의 panic, recover도 알아보자.

## 오류 처리 방법: 기초

- 이전에 봤듯이, Go는 함수에 마지막 반환 값으로 error 타입의 값을 반환해 오류를 처리한다. 이는 전적으로 관례에 의한 것이지만, 절대 위반해서는  
  안되는 강력한 관례이다. 함수가 예상했던대로 수행되면 error로는 nil이 반환된다. 만약 문제가 있었다면 오류 값이 반환된다.  
  호출 함수는 오류 반환값이 nil인지를 확인해 오류 처리를 하거나 해당 값을 그냥 반환한다.

```go
func calcRemainderAndMod(numerator, denominator int) (int, int, error) {
	if denominator == 0 {
		return 0, 0, errors.New("denominator is 0")
	}
	return numerator / denominator, numerator % denominator, nil
}
```

- 새로운 오류는 `error` 패키지에 있는 `New()` 함수를 호출하면서 문자열과 함께 생성된다. 오류 메시지는 대문자를 사용하거나 구두점, 혹은  
  줄 바꿈으로 마무리되어서는 안된다. 대부분의 경우에는 nil이 아닌 오류를 반환할 때 다른 반환 값은 zero-value로 설정한다.  
  Sentinel error를 볼 때 이 규칙에 대한 예외를 볼 수 있다.

- 예외(exception)가 있는 언어들과는 달리, Go는 오류가 반환되는 것을 검출하는 특별한 구문이 없다. 함수가 반환될 때마다 if문을 사용해  
  오류 변수가 nil인지 아닌지 확인한다.

```go
func main() {
	numerator := 20
	denominator := 3
	remainder, mod, err := calcRemainderAndMod(numerator, denominator)
	if err != nil {
		fmt.Println(err)
		os.Exit(1)
	}
	fmt.Println(remainder, mod)
}
```

- `error`는 단일 메소드를 정의하는 내장 인터페이스이다.

```go
type error interface {
	Error() string
}
```

- 해당 인터페이스를 구현하는 모든 것은 오류로 간주된다. 오류가 발생하지 않았음을 나타내기 위해 함수에서 nil을 반환하는 이유는 nil이 모든 인터페이스 타입에  
  대한 zero-value이기 때문이다.

- Go가 예외를 발생시키는 것 대신에 반환된 오류를 사용하는 두 가지 좋은 이유가 있다. 첫 번째로 코드에 하나 이상의 새로운 코드 경로를 추가한다.  
  이 경로는 특히 함수가 예외가 가능하다는 선언이 포함되지 않은 언어에서 명확하지 않은 경우가 있다. 이는 예외가 알맞게 처리되지 않았을 때 놀라운 방법으로  
  crash가 나는 코드를 만들거나 더 심각한 경우에는 crash는 나지만 데이터가 제대로 초기화, 수정, 저장되지는 않는 코드를 만들게 된다.

- 두 번째 이유는 Go의 기능이 동작하는 방법을 보여준다는 것이다. Go 컴파일러는 모든 변수들을 반드시 읽을 수 있어야 한다. 반환 값으로 오류를 만드는 것은  
  개발자에게 오류 조건을 확인하고 처리하는 것을 강제하거나 오류 값으로 `_`를 사용해 오류를 명시적으로 무시하도록 한다.

- 예외 처리는 더 짧은 코드를 생성할 수 있도록 하지만, 더 적은 코드를 사용한다고 해서 코드를 더 쉽게 이해하거나 유지 관리할 수 있는 것은 아니다.  
  앞서 봤듯이 관용적 Go는 코드 라인이 더 많이 생성되더라도 명확한 코드를 선호한다.

- 주목해야 하는 또 다른 사항은 Go에서 코드 흐름의 방식이다. 오류 처리는 if문 내에 들여 작성된다. 하지만 비즈니스 로직은 그렇지 않다.  
  이는 어떤 코드가 _golden path_ 를 따르고, 어떤 코드가 예외적인 조건인지에 대한 빠른 시각적 단서를 제공한다.

---

## 단순 오류에 문자열 사용

- Go의 표준 라이브러리는 문자열로 오류를 생성하는 두 가지 방법을 제공한다. 하나는 `errors.New()` 함수로, 이 함수는 문자열을 받아 `error`를  
  반환한다. 이 문자열은 반환된 오류 인스턴스의 `Error()` 메소드를 호출했을 때 반환된다. 만약 오류를 `fmt.Println()`으로 넘긴다면 자동으로  
  `Error()`가 호출된다.

```go
func doubleEven(i int) (int, error) {
	if i%2 != 0 {
		return 0, errors.New("only even numbers are processed")
	}
	return i * 2, nil
}
```

- 오류를 만드는 두 번째 방법은 `fmt.Errorf()` 함수를 사용하는 것이다. 이 함수는 `fmt.Printf()`에 대한 모든 formatting 동사를  
  사용해 오류를 생성할 수 있다. `errors.New()`와 같이 반환된 오류 인스턴스의 `Error()` 메소드가 호출될 때 문자열이 반환된다.

```go
func doubleEven(i int) (int, error) {
	if i%2 != 0 {
		return 0, fmt.Errorf("%d is not an even number", i)
	}
	return i * 2, nil
}
```

---

## Sentinel Error

- 어떤 오류는 현재 상태의 문제로 처리를 지속할 수 없음을 나타내기 위해 사용된다. Sentinel error의 정의는 아래와 같다.

> Sentinel error는 컴퓨터 프로그래밍에서 특정 값을 사용해 더 이상 처리할 수 없다는 것을 나타내는 관행에서 유례되었다.  
> 그래서 Go에서는 특정 값을 사용해 오류를 나타낸다.

- Sentinel error는 package level에 선언된 몇 가지 변수 중 하나다. 관례에 따라 이름은 `Err`로 시작한다.(`io.EOF` 제외)  
  오류는 읽기 전용으로 취급되며 컴파일러가 이를 강제할 방법은 없지만 해당 값을 변경하는 것은 프로그래밍 오류가 된다.

- Sentinel error는 대게 처리를 시작하거나 지속할 수 없음을 나타낼 때 사용된다. 예를 들어 표준 라이브러리는 zip 파일을 처리하기 위한  
  패키지인 `archive/zip`을 포함한다. 이 패키지는 전달된 데이터가 zip 파일 포맷이 아닐 경우에 반환하는 `ErrFormat`을 포함해 몇 가지  
  오류를 정의한다.

```go
func main() {
	data := []byte("this is not a zip file")
	notAZipFile := bytes.NewReader(data)
	_, err := zip.NewReader(notAZipFile, int64(len(data)))
	if err == zip.ErrFormat {
		fmt.Println("told you so")
	}
}
```

- 표준 라이브러리에 있는 sentinel error의 다른 예시로는 `crypto/rsa` 패키지에 있는 `rsa.ErrMessageTooLong`이다.  
  이 오류는 제공된 public key가 너무 길기에 암호화하지 못함을 나타낸다.

- Sentinel error 하나를 정의하기 전에, sentinel error가 필요한지 확인하자. 하나를 정의하면 그것은 공개 API의 일부가 되며, 이후에  
  모든 이전 버전과 호환되는 배포에서 사용할 수 있도록 해야 한다. 표준 라이브러리에 있는 기존 것 중 하나를 재사용하거나 오류의 반환을 야기한  
  조건에 대한 정보를 포함하는 오류 타입을 정의하는 것이 훨씬 더 좋다. 하지만 더 이상 처리가 가능하지 않고, 오류 상태를 설명하는 문맥적 정보를  
  더 이상 사용할 필요가 없는 특정 상태에 도달했음을 나타내는 오류 조건이 있다면, sentinel error로 처리하는 것이 올바른 선택이다.

- Sentinel error는 `==` 연산자를 사용해 비교할 수 있다.

### Sentinel error를 위한 상수 사용

- 패키지에 아래와 같은 타입을 선언했다고 하자.

```go
package consterr

type Sentinel string

func(s Sentinel) Error() string {
	return string(s)
}
```

- 그리고 아래와 같이 사용한다고 해보자.

```go
package mypkg

const (
	ErrFoo = consterr.Sentinel("foo error")
	ErrBar = consterr.Sentinel("bar error")
)
```

- 마치 함수 호출과 같아보이지만, 실제로는 문자열 리터럴을 `error` 인터페이스를 구현하는 타입으로 전환하는 것에 불과하다.  
  이는 `ErrFoo`와 `ErrBar`의 값 변경을 불가능하게 한다. 언뜻 보기에 좋은 해결책 처럼 보일 수 있다.

- 하지만 이런 관행은 관용적이지 못한 것으로 간주된다. 같은 타입을 사용해 패키지 전반에 걸쳐 상수 오류를 생성한 경우, 오류 문자열이 같다면 두 개의  
  오류가 동일하게 될 것이다. 마치 동일한 값을 가진 문자열 리터럴과 같다. 반면 `errors.New()`로 생성된 오류는 그것 자신, 혹은 명시적으로 해당  
  값을 할당한 변수하고만 동일하게 취급된다. 일반적으로는 거의 확실하게 서로 다른 패키지에서 만들어진 오류들이 같길 원하지 않을 것이다.  
  이를 회피하기 위해 모든 패키지마다 비공개 오류 타입을 만들 수 있겠지만, 이는 너무 많은 상용구를 만들게 된다.

- Sentinel error 패턴은 Go 설계 철학의 또다른 예제이다. Sentinel error는 드물게 사용되어야 하므로 언어 규칙 대신 관례로 처리될 수 있다.  
  즉 공개 package level 변수로 만들자는 것이다. 이는 변수를 수정 가능하게 만들지만, 누군가의 실수로 package level의 공용 변수를 재할당할  
  가능성은 거의 없다. Go에는 언어를 단순하게 유지하고 기능을 추가하는 것보다 개발자와 도구의 신뢰를 높이는게 더 좋다는 철학이 있다.

---

## 오류는 값이다

- 오류는 인터페이스이기 때문에 logging이나 오류 처리를 위한 추가적 정보를 포함해 자신만의 오류를 정의할 수 있다. 예를 들어 사용자에게 다시  
  보고해야 하는 오류의 종류를 나타내기 위해 오류의 일부로 상태 코드를 포함할 수 있다. 이렇게 하면 오류의 원인을 결정하기 위한 문자열 비교를  
  피할 수 있다. 동작 방법을 보자.

```go
type Status int

const (
	InvalidLogin Status = iota + 1
	NotFound
)

type StatusErr struct {
	Status Status
	Message string
}

func (se StatusErr) Error() string {
	return se.Message
}
```

- 이제 문제가 발생하면 더 자세한 사항을 제공하기 위해 `StatusErr`를 사용할 수 있다.

```go
func LoginAndGetData(uid, pwd, file string) ([]byte, error) {
	err := login(uid, pwd)
	if err != nil {
		return nil, StatusErr{
			Status:  InvalidLogin,
			Message: fmt.Sprintf("invalid credentials for user %s", uid),
		}
	}
	data, err := getData(file)
	if err != nil {
		return nil, StatusErr{
			Status:  NotFound,
			Message: fmt.Sprintf("file %s not found", file),
		}
	}
	return data, nil
}
```

- 사용자 정의 오류 타입을 정의하는 경우에도 항상 오류 결과 반환을 위한 타입으로는 `error`를 사용하자. 이는 함수에서 다양한 타입의 오류를  
  반환할 수 있고, 함수 호출자가 특정 오류 타입에 의존하지 않도록 선택할 수 있다.

- 자신만의 오류 타입을 사용한다면 초기화되지 않은 인스턴스를 반환하지 않도록 하자. 이는 사용자 오류의 타입이 되게 하기 위해 변수를 선언하지 않고  
  변수를 반환한다는 의미이다. 이렇게 한다면 어떤 일이 벌어지는지 보자.

```go
func GenerateError(flag bool) error {
	var genErr StatusErr
	if flag {
		genErr = StatusErr{
			Status: NotFound,
		}
	}
	return genErr
}

func main() {
	err := GenerateError(true)
	fmt.Println(err != nil) // true
	err = GenerateError(false)
	fmt.Println(err != nil) // true
}
```

- 위 결과는 pointer type이냐, value type이냐의 문제가 아니다. genErr를 `*StatusErr`로 선언해도 결과는 같다.  
  err가 nil이 아닌 이유는 `error`가 인터페이스이기 때문이다. 이전에 봤듯이 인터페이스가 nil로 간주되려면 기본 타입과 값이 반드시 nil이어야 한다.  
  genErr가 포인터이든 아니든 인터페이스의 기본 타입 부분이 nil이 아니다.

- 위 문제를 고치기 위한 방법이 두 가지 있다. 일반적인 접근은 함수가 성공적으로 완료되었을 때 명시적으로 error 값을 nil로 반환해주는 것이다.

```go
func GenerateError(flag bool) error {
	if flag {
		return StatusErr{
			Status: NotFound,
		}
	}
	return nil
}
```

- 위처럼 하면 반환문에 error 변수가 제대로 정의되었는지를 확인하기 위해 코드의 다른 부분을 읽을 필요가 없다는 이점이 있다.

- 다른 접근법으로 error를 가지는 모든 지역 변수가 error 타입임을 확실하게 하는 것이 있다.

```go
func GenerateError(flag bool) error {
	var genErr error
	if flag {
		genErr = StatusErr{
			Status: NotFound,
		}
	}
	return genErr
}
```

---

## 오류 wrapping

- 오류가 코드를 통해 다시 전달되 때, 해당 오류에 문맥을 추가하고 싶은 경우가 있다. 이런 문맥은 오류를 받는 함수 또는 수행하려는 작업에 대한 내용일 수  
  있다. 추가 정보를 유지하면서 오류를 유지하는 것을 **오류 wrapping** 이라 한다. 일련의 wrapping된 오류를 가질 때 이는 **error chain** 이라 한다.

- Go 표준 라이브러리에는 오류를 wrapping하는 함수가 있고, 이미 앞서 봤다. `fmt.Errorf()` 함수는 특수한 형식 동사 `%w`를 갖고 있다.  
  이 형식 동사는 다른 오류의 형식 지정된 문자열과 원본 오류를 포함하는 형식 지정된 문자열의 오류를 생성하는 데 사용할 수 있다.  
  작성하는 관례는 `%w`를 형식 지정 문자열의 마지막에 두고 `fmt.Errorf()`의 마지막 파라미터로 전달할 wrapping된 오류를 넣는다.

- 표준 라이브러리는 또한 오류를 unwrapping하기 위해 `errors` 패키지에 `errors.Unwrap()` 함수를 제공한다. 오류를 전달하면 만약 해당 오류에  
  wrapping된 오류가 있다면 이를 반환한다. 아래 코드를 보자.

```go
func fileChecker(name string) error {
	f, err := os.Open(name)
	if err != nil {
		return fmt.Errorf("in fileChecker: %w", err)
	}
	f.Close()
	return nil
}

func main() {
	err := fileChecker("not_here.txt")
	if err != nil {
		fmt.Println(err)
		if wrappedErr := errors.Unwrap(err); wrappedErr != nil {
			fmt.Println(wrappedErr)
		}
	}
}
```

- 위 코드의 수행 결과는 아래와 같다.

```
in fileChecker: open not_here.txt: no such file or directory
open not_here.txt: no such file or directory
```

- 사용자 지정 오류 타입으로 오류를 wrapping하려면 오류 타입에서 `Unwrap()` 메소드를 구현해야 한다. 이 메소드는 파라미터가 없고 `error`를  
  반환한다.

```go
type Status string

type StatusErr struct {
	Status Status
	Message string
	err error
}

func (se StatusErr) Error() string {
	return se.Message
}

func (se StatusErr) Unwrap() error {
	return se.err
}
```

- 이제 `StatusErr`로 기본 오류를 wrapping해 사용할 수 있다.

```go
func LoginAndGetData(uid, pwd, file string) ([]byte, error) {
	err := login(uid, pwd)
	if err != nil {
		return nil, StatusErr{
			Status:  "Invalid Login",
			Message: fmt.Sprintf("invalid credentials for user %s", uid),
			err:     err,
		}
	}
	data, err := getData(file)
	if err != nil {
		return nil, StatusErr{
			Status:  "Not Found",
			Message: fmt.Sprintf("file %s not found", file),
			err:     err,
		}
	}
	return data, nil
}
```

- 모든 오류가 wrapping될 필요는 없다. 라이브러리는 처리를 진행할 수 없다는 오류를 반환할 수 있지만, 오류 메시지는 프로그램의 다른 부분에서 필요로  
  하지 않는 구현의 세부 사항을 포함할 수 있다. 이 상황에서는 아주 새로운 오류의 생성을 완벽히 수용하고, 대신 반환할 수 있다. 상황을 이해하고 어떤 것이  
  반환될지를 결정하도록 하자.

---

## `Is`, `As`

- 오류 wrapping은 오류와 관련해 추가 정보를 얻기 위해 유용한 방법이지만 문제가 생길 수 있다. Sentinel error가 wrapping되었다면  
  확인을 위해 `==` 연산자를 사용할 수 없으며, wrapping된 사용자 지정 오류와 일치시키기 위해 type assertion이나 type switch를 사용할  
  수도 없다. Go는 이런 문제를 해결하기 위해 `errors.Is()`와 `errors.As()` 함수를 제공한다.

- 반환된 오류나 wrapping된 모든 오류를 sentinel error 인스턴스와 일치하는지 확인하려면 `errors.Is()`를 사용해야 한다.  
  해당 함수는 확인할 오류와 대응되는 인스턴스를 파라미터로 받는다. 이 함수는 error chain에 제공된 sentinel error와 일치하는 오류가 있다면  
  true를 반환한다. 이 함수의 실행을 보기 위한 간단한 프로그램을 보자.

```go
func fileChecker(name string) error {
	f, err := os.Open(name)
	if err != nil {
		return fmt.Errorf("in fileChecker: %w", err)
	}
	f.Close()
	return nil
}

func main() {
	err := fileChecker("not_here.txt")
	if err != nil {
		if errors.Is(err, os.ErrNotExist) {
			fmt.Println("That file does not exist") // 출력됨
		}
	}
}
```

- 기본적으로 `errors.Is()`는 지정된 오류와 wrapping된 오류를 비교하기 위해 `==`를 사용한다. 만약 직접 정의한 오류 타입이 해당 동작을 하지  
  않을 경우, 아래처럼 오류 타입에 `Is()` 메소드를 구현하도록 하자.

```go
type MyErr struct {
	Codes []int
}

func (m MyErr) Error() string {
	return fmt.Sprintf("codes: %v", m.Codes)
}

func (m MyErr) Is(target error) bool {
	if m2, ok := target.(MyErr); ok {
		return reflect.DeepEqual(m, m2)
	}
	return false
}
```

- 자체 `Is()` 메소드를 구현하는 것의 다른 용도는 동일한 인스턴스가 아닌 오류에 대해 비교가 가능하게 한다.  
  일부 동일한 항목을 가지는 오류와 일치하는 filter 인스턴스를 지정해 오류를 일치시키는 패턴을 만들 수 있다. 아래 코드를 보자.

```go
type ResourceErr struct {
	Resource string
	Code int
}

func (re ResourceErr) Error() string {
	return fmt.Sprintf("%s: %d", re.Resource, re.Code)
}

func (re ResourceErr) Is(target error) bool {
	if other, ok := target.(ResourceErr); ok {
		ignoreResource := other.Resource == ""
		ignoreCode := other.Code == 0
		matchResource := other.Resource == re.Resource
		matchCode := other.Code == re.Code
		return matchResource && matchCode ||
			matchResource && ignoreCode ||
			ignoreResource && matchCode
	}
	return false
}
```

- `errors.As()`는 반환된 오류가 특정 타입과 일치하는지 확인할 수 있다. 해당 함수는 두 개의 파라미터를 받는데 첫 번째는 검사할 오류이고, 두 번째는  
  찾고자 하는 타입의 변수를 가리키는 포인터다. 이 함수가 true를 반환하면 error chain에 있는 오류와 일치하는 것을 찾았다는 것이고, 일치하는 오류는  
  두 번째 파라미터로 할당된다. 만약 false를 반환하면 error chain에서 일치하는 오류를 못 찾았다는 것이다.

```go
func main() {
	err := AFunctionThatReturnsAnError()
	var myErr MyErr
	if errors.As(err, &myErr) {
		fmt.Println(myErr.Codes)
	}
}
```

- 위 코드에서는 특정 타입의 변수를 zero-value로 설정해 선언하기 위해 var 키워드를 사용했다. 그리고 해당 변수의 포인터를 `errors.As()`의 두 번째  
  파라미터로 전달한다.

- `errors.As()`의 두 번째 파라미터로 꼭 오류 타입의 포인터 변수를 전달할 필요는 없다. 인터페이스를 충족하는 오류를 찾기 위해 인터페이스의 포인터를  
  전달할 수도 있다.

```go
func main() {
	err := AFunctionThatReturnsAnError()
	var coder interface {
		Code() int
	}
	if errors.As(err, &coder) {
		fmt.Println(coder.Code())
	}
}
```

- 위에서는 익명 인터페이스를 사용했지만, 모든 인터페이스의 타입이 사용 가능하다.

> `errors.As()`의 두 번째 파라미터로 오류의 포인터아 인터페이스 포인터가 아닌 다른 것을 전달하면 panic을 일으킨다.

- 기본 `errors.Is()`의 비교를 `Is()` 메소드를 구현함으로써 재정의할 수 있듯이, 기본 `errors.As()`의 비교도 해당 오류 타입 내에  
  `As()` 메소드를 구현해 재정의할 수 있다. `As()`를 구현하는 것은 사소하지 않고, reflection이 요구된다. 이는 하나의 오류 타입을 일치시키고  
  다른 타입을 반환하는 경우와 같은 특수한 상황에서만 사용하도록 하자.

> 특정 인스턴스나 값을 찾을 때 `errors.Is()`를 사용하고, 특정 타입을 찾을 때는 `errors.As()`를 사용하자.

---

## defer로 오류 wrapping

- 가끔씩 아래와 같이 동일한 메시지로 여러 오류를 wrapping한 것을 발견할 때가 있다.

```go
func DoSomeThings(val1 int, val2 string) (string, error) {
	val3, err := doThing1(val1)
	if err != nil {
		return "", fmt.Errorf("in DoSomeThings: %w", err)
	}
	val4, err := doThing2(val2)
	if err != nil {
		return "", fmt.Errorf("in DoSomeThings: %w", err)
	}
	result, err := doThing3(val3, val4)
	if err != nil {
		return "", fmt.Errorf("in DoSomeThings: %w", err)
	}
	return result, nil
}
```

- 이를 defer를 사용해 더 간단히 작성할 수 있다.

```go
func DoSomeThings(val1 int, val2 string) (_ string, err error) {
	defer func() {
		if err != nil {
			err = fmt.Errorf("in DoSomeThings: %w", err)
		}
	}()
	val3, err := doThing1(val1)
	if err != nil {
		return "", err
	}
	val4, err := doThing2(val2)
	if err != nil {
		return "", err
	}
	return doThing3(val3, val4)
}
```

- 코드를 보면 defer된 함수에서 err를 참조할 수 있도록 반환 값에 이름을 부여했다. 만약 단일 반환 값에만 이름을 지정하고 싶은 경우, 일단  
  이름을 지정하면 모든 반환값에 대해 이름을 지정해야 하므로 명시적으로 할당하지 않을 문자열 반환값에는 `_`를 지정했다.

- defer closure에서는 오류가 반환되었는지 검사한다. 만약 오류가 반환되었다면 함수 내에서 검출된 오류를 나타내는 메시지와 함께 원본 오류를  
  wrapping한 새로운 error를 재할당해준다.

- 이런 방식은 같은 메시지로 wrapping된 모든 오류를 처리하는 경우에 잘 동작한다. 오류를 일으킨 것이 무엇이었는지에 대한 더 많은 내용을  
  제공하기 위해 wrapping된 오류를 반환하려면 모든 `fmt.Errorf()`에 지정된 메시지와 일반 메시지를 모두 넣자.

---
